name: bricks
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  injectable: ^2.3.2
  injectable_generator: ^2.4.1
  dart_mappable: ^4.0.0
  flutter_bloc: ^8.1.3
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.1
  json_annotation: ^4.8.1
  build_runner: ^2.4.6
  get_it: ^7.6.4
  dart_mappable_builder: ^4.0.0
  meta: ^1.9.1
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  intl: ^0.18.1
  slang: ^3.25.0
  slang_gpt: ^0.10.0
  slang_flutter: ^3.25.0
  slang_build_runner: ^3.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
